version: '3.8'

services:
  mysql:
    container_name: pizza_shop-database
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizza-shop
      MYSQL_PASSWORD: pizza-shop
      MYSQL_USER: pizza-shop
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3366:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - pizzashop-network

networks:
  pizzashop-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
